#! /bin/sh

if [ $# -ne 1 -o ! -d "$1" ] ; then
    echo "usage: encode.sh PATH-TO-UNIDATA" 1>&2
    exit 1
fi

set -e
UNIDATA="$1"

export LANG=C
make all

echo ";; autogenerated, do not change manually" > generated-data.asm
echo ";; autogenerated, do not change manually" > generated-code.asm

grep '^[0-9A-Z].*White_Space' "$UNIDATA/PropList.txt" \
  | cut -d' ' -f1 \
  | ./encode -asm white_space > tmp.asm
sed -n '/;;.*data start/,/;;.*data end/p' tmp.asm >> generated-data.asm
sed -n '/;;.*code start/,/;;.*code end/p' tmp.asm >> generated-code.asm

grep '^[0-9A-Z].*Alphabetic' "$UNIDATA/DerivedCoreProperties.txt" \
  | cut -d' ' -f1 \
  | ./encode -asm alphabetic > tmp.asm
sed -n '/;;.*data start/,/;;.*data end/p' tmp.asm >> generated-data.asm
sed -n '/;;.*code start/,/;;.*code end/p' tmp.asm >> generated-code.asm
